"""Sequence preset generation.

Aspect ratio has to come from a `.sqpreset`: `SequenceSettings` exposes no
frame-size setter, so `createSequenceWithPresetPath` is the only route to a
1080x1920 sequence.

Premiere's own Social presets (9x16, 1x1, 4x5) exist but are **30 fps only**, which
is no use for 25 or 59.94 fps work. The format is small, plain XML, so generating
one per (aspect, frame rate) removes that limitation entirely.

Verified against Adobe's shipped presets: the tick maths below reproduces their
VideoFrameRate exactly for 23.976, 24, 25, 29.97, 30, 50, 59.94 and 60.
"""

from __future__ import annotations

from pathlib import Path
from xml.sax.saxutils import escape

from .timebase import Timebase

# Premiere counts time in ticks; this many per second. VideoFrameRate is the
# number of ticks in one frame.
TICKS_PER_SECOND = 254016000000

# The editing mode every shipped preset uses. Identical across all 392 of them.
EDITING_MODE_MAC = "795454d9-d3c2-429d-9474-923ab13b7018"
EDITING_MODE_WIN = "9678AF98-A7B7-4bdb-B477-7AC9C8DF4A4E"

# How timecode is DISPLAYED, read off Adobe's own presets. Cosmetic only -- it
# does not affect timing -- so an unmapped rate falling back is harmless.
TIME_DISPLAY: dict[tuple[int, int], int] = {
    (24000, 1001): 110,   # 23.976
    (24, 1): 100,
    (25, 1): 101,
    (30000, 1001): 102,   # 29.97 drop frame
    (30, 1): 104,
    (48, 1): 113,
    (50, 1): 105,
    (60000, 1001): 106,   # 59.94
    (60, 1): 108,
}
DEFAULT_TIME_DISPLAY = 104

_AUDIO_TRACK = (
    '{"mAssign":0,"mAudioSends":[],"mChannelType":1,"mIsOpen":false,"mIsSubmix":false,'
    '"mKeyframeMode":true,"mLocked":false,"mMatrix":[],"mMute":false,"mName":"","mPan":0,'
    '"mPannerAssignments":[],"mSolo":false,"mSyncLock":true,"mTargeted":false,'
    '"mTrackID":-1,"mVolume":1}'
)


def ticks_per_frame(tb: Timebase) -> int:
    """Ticks in one frame. Exact integer for every broadcast rate."""
    return TICKS_PER_SECOND * tb.fps_den // tb.fps_num


def time_display_code(tb: Timebase) -> int:
    return TIME_DISPLAY.get((tb.fps_num, tb.fps_den), DEFAULT_TIME_DISPLAY)


def preset_xml(
    name: str,
    width: int,
    height: int,
    timebase: Timebase,
    video_tracks: int = 3,
    audio_tracks: int = 2,
    description: str = "",
) -> str:
    """A complete .sqpreset document."""
    if width <= 0 or height <= 0:
        raise ValueError(f"invalid frame size {width}x{height}")

    audio = ",".join([_AUDIO_TRACK] * max(1, audio_tracks))
    label = escape(name)
    blurb = escape(description or f"{width}x{height} at {timebase.fps:.3f} fps. Generated by AutoEdit.")

    return f"""<?xml version="1.0" encoding="UTF-8"?>
<PremiereData Version="3">
\t<SequencePreset ObjectRef="1"/>
\t<SequencePreset ObjectID="1" ClassID="5e73dd7e-4f86-4917-80eb-08ddb2f4a5f3" Version="9">
\t\t<VideoTimeDisplay>{time_display_code(timebase)}</VideoTimeDisplay>
\t\t<AudioTimeDisplay>200</AudioTimeDisplay>
\t\t<VideoFrameRate>{ticks_per_frame(timebase)}</VideoFrameRate>
\t\t<VideoFrameSize>0,0,{width},{height}</VideoFrameSize>
\t\t<AudioFrameRate>5292000</AudioFrameRate>
\t\t<AudioChannelType>1</AudioChannelType>
\t\t<VideoFieldType>0</VideoFieldType>
\t\t<WorkingColorSpace>{{"baseColorProfile":{{"colorProfileName":"BT.709 RGB Full"}},"baseProfileType":1}}</WorkingColorSpace>
\t\t<Names Version="1">
\t\t\t<NameItem Version="1" Index="0">
\t\t\t\t<First>en_US</First>
\t\t\t\t<Second>{label}</Second>
\t\t\t</NameItem>
\t\t</Names>
\t\t<First>en_US</First>
\t\t<Second>{blurb}</Second>
\t\t<EditingModeGUID.Mac>{EDITING_MODE_MAC}</EditingModeGUID.Mac>
\t\t<EditingModeGUID.Win>{EDITING_MODE_WIN}</EditingModeGUID.Win>
\t\t<PreviewPresetFileName.Mac>QuickTime</PreviewPresetFileName.Mac>
\t\t<PreviewPresetVideoCodec.Mac>1634755443</PreviewPresetVideoCodec.Mac>
\t\t<PreviewPresetFileName.Win>QuickTime</PreviewPresetFileName.Win>
\t\t<PreviewPresetVideoCodec.Win>1634755443</PreviewPresetVideoCodec.Win>
\t\t<VideoPixelAspectRatio>1,1</VideoPixelAspectRatio>
\t\t<VideoUseMaxBitDepth>false</VideoUseMaxBitDepth>
\t\t<VideoUseMaxRenderQuality>false</VideoUseMaxRenderQuality>
\t\t<VideoAllowLinearCompositing>true</VideoAllowLinearCompositing>
\t\t<AdaptiveNumChannels>2</AdaptiveNumChannels>
\t\t<InitialNumberOfVideoTracks>{max(1, video_tracks)}</InitialNumberOfVideoTracks>
\t\t<AudioTracks>[{audio}]</AudioTracks>
\t\t<VideoTracks>[]</VideoTracks>
\t\t<PreviewVideoFrameSize>0,0,{width},{height}</PreviewVideoFrameSize>
\t\t<SequenceWorkingColorSpace>{{"workingSpaceConfigVersion":1,"workingSpaceID":"BT.709 RGB Full","workingSpaceIsLinearized":0}}</SequenceWorkingColorSpace>
\t\t<AutoToneMapEnabled>true</AutoToneMapEnabled>
\t</SequencePreset>
</PremiereData>
"""


def write_preset(
    out_path: str | Path,
    name: str,
    width: int,
    height: int,
    timebase: Timebase,
    video_tracks: int = 3,
    audio_tracks: int = 2,
) -> Path:
    """Write a preset beside the plan that references it.

    Deliberately co-located with the plan rather than cached elsewhere: the plan
    stores an absolute presetPath, and keeping the two together means the pair can
    be moved to another machine without the reference breaking.
    """
    path = Path(out_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(preset_xml(name, width, height, timebase, video_tracks, audio_tracks))
    return path
